name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Thank you for sharing this contribution, but since this repository is a read-only mirror, it does not accept code contributions. This pull request will be closed."
